name: Deploy to Virtual Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install npm dependencies
      run:  npm install
      working-directory: ./CandidateChallenge

    - name: Archive Repository
      uses: montudor/action-zip@v0.3.0
      with:
        args: -r deploy_bundle.zip

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy bundle to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "deploy_bundle.zip"
        target: "~/"

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
          unzip -o deploy_bundle.zip -d ~/Abhay
          cd ~/Abhay/CandidateChallenge
          npm install
          sudo pm2 start index.js
        EOF