name: Deploy to Virtual Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@20.2.74.69 << 'EOF'
          mkdir Abhay
          cd Abhay
          git clone https://github.com/Blax1s/CandidateChallenge.git
          cd CandidateChallenge
          npm install
          sudo node index.js
        EOF